name = "custom-link-hub-v5"
compatibility_date = "2026-04-07"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "custom-link-hub"
database_id = "6f99bea2-b00d-40ad-a641-8b45b18d6457"

[[kv_namespaces]]
binding = "PAGE_CACHE"
id = "1f99f6b0a64e470ebc6411f6e13cc64c"
preview_id = "354e961032c64b5e881fdddf5c88eeb7"

[[services]]
binding = "MAILER"
service = "fanlynks-mailer"

[vars]
APP_NAME = "Fan Lynks"
APP_ORIGIN = "https://fanlynks.com"
CUSTOMER_SIGNUP_MODE = "invite_only"
