name = "fanlynks-mailer"
main = "src/index.ts"
compatibility_date = "2026-04-07"
workers_dev = false

[[send_email]]
name = "EMAIL"
allowed_sender_addresses = ["accounts@fanlynks.com"]

[vars]
EMAIL_SENDER = "accounts@fanlynks.com"
APP_ORIGIN = "https://fanlynks.com"
